version: '3'

services:

  worker:
    build:
      context: .
      dockerfile: dockerfile
    image: &img worker
    depends_on:
      - redis
    restart: 'always'
    volumes:
      - ./tap_pream:/tap_pream
    working_dir: /tap_pream
    command: tail -f /dev/null

  beat:
    build:
      context: .
      dockerfile: dockerfile
    image: *img
    command: tail -f /dev/null
    depends_on:
      - redis
      - worker
    volumes:
      - ./tap_pream:/tap_pream
    restart: 'always'
    working_dir: /tap_pream

  redis:
    image: redis

  flower:
    build: .
    image: *img
    command: ["flower", "--broker=redis://redis:6379/0", "--port=5555"]
    ports:
      - 5555:5555
    depends_on:
      - worker
      - redis