version: '3'

services:

  worker:
    build:
      context: .
      dockerfile: dockerfile
    image: &img worker
    depends_on:
      - redis
    restart: 'no'
    volumes:
      - ./tap_pream:/tap_pream
    working_dir: /tap_pream
    command: tail -f /dev/null

  beat:
    build:
      context: .
      dockerfile: dockerfile
    image: *img
    command: [celery, beat, --app=celery_app.app, --loglevel=INFO]
    depends_on:
      - redis
    volumes:
      - ./tap_pream:/tap_pream
    restart: 'no'
    working_dir: /tap_pream

  redis:
    image: redis