version: '3'

services:

  worker:
    build:
      context: .
      dockerfile: dockerfile
    image: worker
    depends_on:
      - redis
    restart: 'no'
    volumes:
      - ./tap_pream:/tap_pream
    working_dir: /tap_pream
    command: tail -f /dev/null

  redis:
    image: redis